
@purpuraPrivate_HostAddress = http://localhost:3030


### Genre methods


### create Genre
POST {{purpuraPrivate_HostAddress}}/apiprivate/createGenre
Content-Type: application/json

{
    "name": "Reggaeton",
    "description": "Reggaeton is a music genre that originated in Puerto Rico during the late 1990s",
    "color":"#EBA329"
}


### update Genre
PUT {{purpuraPrivate_HostAddress}}/apiprivate/updateGenre
Content-Type: application/json

{
    "id": "696a75a0-4b40-4d57-8477-1fec1de0f9ae",
    "name": "Rock",
    "description": "Rock music is a broad genre of popular music that originated as rock and roll, great genre",
    "color":"#FFEC33"
}

### delete Genre
DELETE  {{purpuraPrivate_HostAddress}}/apiprivate/deleteGenre
Content-Type: application/json

{
    "id": "696a75a0-4b40-4d57-8477-1fec1de0f9ae",
    "name": "Rock",
    "description": "Rock music is a broad genre of popular music that originated as rock and roll, great genre",
    "color":"#FFEC33"
}




### Artist Methods

### Create Artist
POST {{purpuraPrivate_HostAddress}}/apiprivate/createArtist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbkRhdGEiOnsidXNlcklkIjoiMTA5Mjg1MDUwMyIsImVtYWlsIjoidmFyZ2FzbG9haXphY3Jpc3RpYW5AZ21haWwuY29tIn0sImlhdCI6MTczNjE5OTY3NCwiZXhwIjoxNzM2MjAzMjc0fQ.0Kw8CkCEnx-drhJrA4eAh56ekNEltZjWzxNADTr_VII
Content-Type: application/json

{
    "name": "The Weeknd",
    "description": "The Weeknd is a Canadian singer, songwriter, and record producer"
}


### Update Artist
PUT {{purpuraPrivate_HostAddress}}/apiprivate/updateArtist
Content-Type: application/json

{
    "id": "66f2e1b2-f944-4463-b8ef-26583bdd2a8",
    "name": "The Beatles",
    "description": "The Beatles were one of the greatest English rock band formed in Liverpool in 1960, great band"
}

### Delete Artist
DELETE {{purpuraPrivate_HostAddress}}/apiprivate/deleteArtist
Content-Type: application/json

{
    "id": "00f4e6d1-42b8-4da0-b54d-a0a7f59ad6f2"
}


### Album Methods

### Create Album
POST {{purpuraPrivate_HostAddress}}/apiprivate/createAlbum
Content-Type: application/json

{
    "name": "Abbey Road (Deluxe)",
    "description": "Abbey Road is the eleventh studio album by the English rock band the Beatles",
    "releaseDate": "1969-09-26",
    "genreId":"633a9991-5a77-463a-bb15-ff1c7d577410", 
    "writerName":"John Lennon, Paul McCartney", 
    "producerName":"John Lennon, Paul McCartney",
    "recordLabel":"Apple Records",
    "artistId": "66f2e1b2-f944-4463-b8ef-26583bdd2a8a"
}

### Update Album
PUT {{purpuraPrivate_HostAddress}}/apiprivate/updateAlbum
Content-Type: application/json

{
    "id":"dc199c28-c0ad-4b76-96ad-b5d702b4dbb4",
    "name": "Abbey Road [deluxe]",
    "description": "Abbey Road is the eleventh studio album by the English rock band the Beatles",
    "releaseDate": "1969-09-26",
    "genreId":"633a9991-5a77-463a-bb15-ff1c7d577410", 
    "writerName":"John Lennon, Paul McCartney", 
    "producerName":"John Lennon, Paul McCartney, Ringo Starr",
    "recordLabel":"Apple Records",
    "artistId": "66f2e1b2-f944-4463-b8ef-26583bdd2a8a"
}


### Delete Album
DELETE {{purpuraPrivate_HostAddress}}/apiprivate/deleteAlbum
Content-Type: application/json

{
    "id":"dc199c28-c0ad-4b76-96ad-b5d702b4dbb4"
}


### Song Methods

### Create a single song
POST {{purpuraPrivate_HostAddress}}/apiprivate/createSongSingle
Content-Type: application/json

{
    "name": "Come Together",
    "description": "Come Together is a song by the English rock band the Beatles",
    "releaseDate": "1969-09-26",
    "genreId":"633a9991-5a77-463a-bb15-ff1c7d577410", 
    "writerName":"John Lennon, Paul McCartney", 
    "producerName":"John Lennon, Paul McCartney",
    "recordLabel":"Apple Records",
    "artistId": "66f2e1b2-f944-4463-b8ef-26583bdd2a8a",
    "albumId": "dc199c28-c0ad-4b76-96ad-b5d702b4dbb4"
}

### Create a single song
POST {{purpuraPrivate_HostAddress}}/apiprivate/createSongSingle
Content-Type: application/json

{
    "name": "Luna",
    "description": "Luna is a song by the Colombian singer-songwriter Feid",
    "lyrics":"Te busco y no sé dónde estás",
    "releaseDate": "2023-09-26",
    "genres":["dba2112f-d4b7-4ada-8001-76f613614587", "1a1e4dbd-51a7-4867-aafc-7d9a589c4f52"], 
    "artists":["480f0c66-6ef5-44ef-85bb-b58184bc102a"],
    "writerName":"Salomón Hoyos", 
    "producerName":"Salomón Hoyos, ATL Jacob",
    "duration": "197",
    "recordLabel":"Universal Music Latino",
    "audioUrl":"https://www.youtube.com/watch?v=x2oUajHp8pg"
}

### Add song to an album
POST {{purpuraPrivate_HostAddress}}/apiprivate/addSongToAlbum
Content-Type: application/json

{
    "name": "Here Comes The Sun",
    "lyrics":"Here comes the sun, doo-doo-doo-doo",
    "albumId": "e121cec8-a4c1-449a-b0ec-6707a2aad53f",
    "duration": "185", 
    "genres":["633a9991-5a77-463a-bb15-ff1c7d577410"], 
    "artists":["66f2e1b2-f944-4463-b8ef-26583bdd2a8a"],
    "audioUrl":"https://www.youtube.com/watch?v=KQetemT1sWc"
}
### Update a song
PUT {{purpuraPrivate_HostAddress}}/apiprivate/updateSong
Content-Type: application/json

{
    "id":"fb640cdf-0ac9-4713-8210-1da24948fbda",
    "name": "Here Comes The Sun",
    "lyrics":"Here comes the sun, doo-doo-doo-doo, Here comes the sun, and I say",
    "albumId": "e121cec8-a4c1-449a-b0ec-6707a2aad53f",
    "duration": "188", 
    "genres":["dba2112f-d4b7-4ada-8001-76f613614587"], 
    "artists":["480f0c66-6ef5-44ef-85bb-b58184bc102a"],
    "audioUrl":"https://www.youtube.com/watch?v=KQetemT1sWc"
}


### delete a song
DELETE {{purpuraPrivate_HostAddress}}/apiprivate/deleteSong
Content-Type: application/json

{
    "id":"a8aa599e-864b-4e57-9c26-bc8dde6087d6"
}
### remove a genre from a song
PUT {{purpuraPrivate_HostAddress}}/apiprivate/removeGenreFromSong
Content-Type: application/json

{
    "id":"fb640cdf-0ac9-4713-8210-1da24948fbda",
    "genreId":"dba2112f-d4b7-4ada-8001-76f613614587"
}

### remove a artist from a song
PUT {{purpuraPrivate_HostAddress}}/apiprivate/removeArtistFromSong
Content-Type: application/json

{
    "id":"fb640cdf-0ac9-4713-8210-1da24948fbda",
    "artistId":"480f0c66-6ef5-44ef-85bb-b58184bc102a"
}

### delete a song from an album
DELETE {{purpuraPrivate_HostAddress}}/apiprivate/removeSongFromAlbum
Content-Type: application/json

{
    "id":"c2d98ab3-af50-49d0-8af6-c106866f8235"
}




### Login Test
POST {{purpuraPrivate_HostAddress}}/apiprivate/login/admin
Content-Type: application/json

{
    "email": "",
    "password":""
}

### logout Test
POST {{purpuraPrivate_HostAddress}}/apiprivate/logout/admin
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWZyZXNoVG9rZW5EYXRhIjp7InVzZXJJZCI6IjEwOTI4NTA1MDMiLCJlbWFpbCI6InZhcmdhc2xvYWl6YWNyaXN0aWFuQGdtYWlsLmNvbSIsInNlc3Npb25JZCI6ImQ4ZDQ3OTg0LWNiOGEtNGJmYi1iM2EyLWI1YTA4ZGRmYjIzYyJ9LCJpYXQiOjE3MzYxOTMwNTMsImV4cCI6MTczNjE5MzE3M30.K1lHiuOg2D5osxTYwkpb_634qFwAnC87vLAPrErtf-s"
}




### refresh token
PUT {{purpuraPrivate_HostAddress}}/apiprivate/refresh/admin
content-type: application/json

{
    "refreshToken": ""
}